name: adb_wifi_connector
description: ADB WiFi connection tool
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.0
  system_tray: ^2.0.3
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.16.8

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.ico
    - assets/adb/adb.exe
    - assets/adb/AdbWinApi.dll
    - assets/adb/AdbWinUsbApi.dll 
msix_config:
  display_name: adb wifi connector
  publisher_display_name: NodChan
  identity_name: NodChan.adbwificonnector
  msix_version: 1.2.1.0
  logo_path: assets\app_icon.ico
  enable_at_startup: true
  store: true #如果store: true（当前你的配置），这表示要发布到Microsoft Store，此时不会生成开发数字证书,如果是开发测试用途，应该设置为store: false
  publisher: CN=FD745275-0A7D-4275-A3E8-96892D1C2AA6
  # capabilities: internetClient, location, microphone, webcam